### ISSUE TITLE
Change storage folder for sitemaps

### ISSUE THREAD

**Issue by stefandoorn** [stefandoorn/sitemap-plugin#104]
Should probably be put in `var/storage/sylius-sitemap` or something to keep of with conventions

_Originally posted by @loevgaard in https://github.com/stefandoorn/sitemap-plugin/pull/99_

**Comment by loevgaard** [comment]
You asked if you could read about best practices somewhere regarding this. I am not sure I can find something like that, but from the linux world and also in SF4 apps, the `var` dir is meant for logs, caches, and files of all sorts. Hence `var` is the right choice. Within the `var` you will always have some kind of 'namespace', i.e. a folder representing a group of files. It could be argued that the `storage` part could be skipped, but I have seen a few other bundles saving files to `var/storage/[something]`. Those are my 2 cents :)
