### ISSUE TITLE
Incompatibility with Symfony 5

### ISSUE THREAD

**Issue by lruozzi9** [stefandoorn/sitemap-plugin#148]
Hi!
It's impossible to use this plugin with Symfony 5.2. The issue is due to the use of the service 'templating' that is no more available in Symfony 5 ([Check for example Sylius upgrade guide](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.9.md#upgrades-symfony-to-v52)).

**Comment by stefandoorn** [comment]
Should be working now on `master` branch and `v2.0.0-alpha.1` release. Thanks!
