### ISSUE TITLE
Upgrade test infrastructure to new Symfony directory structure

### ISSUE THREAD

**Issue by stefandoorn** [stefandoorn/sitemap-plugin#155]
Before we can bump the minimum Sylius version to e.g. 1.8 (latest supported version) the whole test infrastructure needs to be updated to the latest version similar to PluginSkeleton. Current version is e.g. using the old Kernel.

**Comment by stefandoorn** [comment]
@mmenozzi Unfortunately this is one of the things that needs to be done before we can move to Sylius ^1.8..

**Comment by mmenozzi** [comment]
👍

**Comment by stefandoorn** [comment]
Thanks @vicla31
