### ISSUE TITLE
update recipes

### ISSUE THREAD

**Issue by Snowbaha** [stefandoorn/sitemap-plugin#173]
Hello,

You should update the recipies with the good config file name :)

I stuck for 1 hour to undersntand it is missing the "a" in `config.yaml`

https://github.com/symfony/recipes-contrib/edit/master/stefandoorn/sitemap-plugin/1.0/config/packages/sitemap_plugin.yaml

AND Update Readme with good command 
![image](https://user-images.githubusercontent.com/3284722/122885746-a59f1a00-d33f-11eb-8241-13b7b15d73e1.png)

It is 
```bash
$ php bin/console sylius:sitemap:generate
```
not with "-index" in the alpha5 for me.

**Comment by stefandoorn** [comment]
Are you able to submit a PR for both things? 

I think the recipe links to version 1.0, and the file extension got changed in v2.

**Comment by Snowbaha** [comment]
I don't really know how it works. I wanted to change but I think it can break the 1.* so maybe when you will do the v2 stable ?

**Comment by stefandoorn** [comment]
I actually have no clue myself either, someone else provided that PR to Symfony. @Margauxfeslard could you be of help here to us?

**Comment by ehibes** [comment]
[https://github.com/symfony/recipes-contrib/pull/1448](https://github.com/symfony/recipes-contrib/pull/1448)

**Comment by stefandoorn** [comment]
@vvasiloi merged it I see :-)

**Comment by stefandoorn** [comment]
Thanks @ehibes !
