### ISSUE TITLE
Problem on install with Sylius 1.10 

### ISSUE THREAD

**Issue by disvroian** [stefandoorn/sitemap-plugin#175]
composer require stefandoorn/sitemap-plugin

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /var/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/Configuration.php on line 18 and at least 1 expected in /var/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
!!  Stack trace:
!!  #0 /var/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/Configuration.php(18): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
!!  #1 /var/vendor/symfony/config/Definition/Processor.php(50): SitemapPlugin\DependencyInjection\Configuration->getConfigTreeBuilder()
!!  #2 /var/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration()
!!  #3 /var/vendor/stefandoorn/sitemap-plugin/src/DependencyInjection/Si in /var/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
!!
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by stefandoorn** [comment]
I guess it's trying to install v1. Could you try the v2 alpha version? I soon want to release it, but need to do some last improvements..

**Comment by stefandoorn** [comment]
You should be good using `v2.0.0-alpha.6` now with Sylius 1.10.
