### ISSUE TITLE
[Incompatibility] Doctrine/dbal conflict

### ISSUE THREAD

**Issue by Jibbarth** [stefandoorn/sitemap-plugin#194]
Hi @stefandoorn 

I have a sylius 1.10 on php8, and sf5.4. 

I initially added this plugin targetting [dev-master#6b039dbb15e9c1c8c177e9af86609c5eb3815b22](https://github.com/stefandoorn/sitemap-plugin/commit/6b039dbb15e9c1c8c177e9af86609c5eb3815b22) as it's allow php8. 

I can't update to latest release `v2.0.0-alpha.6`, because there is a conflict with `doctrine/dbal >2.13`. Some symfony packages (like cache) have conflicts with `doctrine/dbal < 2.13.1` for 5.4 version

I was unable to find any reason for this conflict. Do you have any clue ?

**Comment by stefandoorn** [comment]
Ah.. I think we can remove the `conflict` here, it's better that Sylius handles that, this plugin doesn't mind too much about it. I will take it out now and release `v2.0.0-alpha.7`.
