### ISSUE TITLE
Configure 'changefreq' per type

### ISSUE THREAD

**Issue by euperia** [stefandoorn/sitemap-plugin#199]
Is it possible to configure a different `changefreq` for each of the different types?  

For example, the `cms_pages.xml` has a changefreq of 'daily' but I'd like to change that to something longer.

**Comment by stefandoorn** [comment]
Unfortunately the only way that's currently supported is by overriding / implementing your own providers. It should not be too difficult following the decorator pattern though: https://symfony.com/doc/current/service_container/service_decoration.html - so you don't have to do the whole generation also again.

It might be a nice feature to be able to configure it somehow without breaking change - would you be open up to try a PR on it?
