### ISSUE TITLE
Sitemap index will have duplicated sitemap urls if you have more than one channel

### ISSUE THREAD

**Issue by lruozzi9** [stefandoorn/sitemap-plugin#208]
This is due to the SitemapIndexBuilder, the indexProvider::providers array will never be cleared after one channel, so it will continue to add providers to them, this will so generate duplicated references to the same sitemap URL provider.

**Comment by stefandoorn** [comment]
Hi @lruozzi9 Hasn't this been solved in https://github.com/stefandoorn/sitemap-plugin/pull/198? That should be part of one of the last releases also.

**Comment by lruozzi9** [comment]
Whops, it just looks like the same problem! I will try to upgrade the plugin.

**Comment by lruozzi9** [comment]
It works! Thanks, @stefandoorn.

**Comment by stefandoorn** [comment]
Great!
