### ISSUE TITLE
Can't change providers option

### ISSUE THREAD

**Issue by sweoggy** [stefandoorn/sitemap-plugin#22]
When trying to set taxons provider to false I get an exception:

> InvalidConfigurationException
> Unrecognized option "providers" under "sylius_sitemap"

My config.yml:
```
sitemap:
    providers:
        taxons: false
```

**Comment by sweoggy** [comment]
Nevermind, was on 1.0.1 instead of dev-master

**Comment by stefandoorn** [comment]
:-) Maybe I should file a new release :)

**Comment by stefandoorn** [comment]
Done!
