### ISSUE TITLE
Incompatible with Twig 3.x due to spaceless tag

### ISSUE THREAD

**Issue by wdttilburg** [stefandoorn/sitemap-plugin#227]
Hi,

The spaceless tag is used in two twig templates:
- src/Resources/views/index.xml.twig
- src/Resources/views/show.xml.twig

This is deprecated in Twig 2.7 and removed in Twig 3.0, causing an error when generating the sitemap.
https://twig.symfony.com/doc/2.x/deprecated.html#tags

I ran into this issue with version sitemap-plugin v2.0.1

**Comment by stefandoorn** [comment]
I see I changed that already in `master`: https://github.com/stefandoorn/sitemap-plugin/commit/fd679af6d79bb841a0e03cd09d7574be4cbb4729.

Not released yet, I'll have a look soon whether I can tag a new version to include this. Downside is that change doesn't allow people to use Twig <2.9 anymore, although I'm not sure that is a big issue..

**Comment by stefandoorn** [comment]
Did some maintenance today, will look into a new release soon.

**Comment by stefandoorn** [comment]
Included in https://github.com/stefandoorn/sitemap-plugin/releases/tag/v2.1.0!
