### ISSUE TITLE
Fix controller route

### ISSUE THREAD

**Issue by SquareInnov** [stefandoorn/sitemap-plugin#234]
The controller for URI "/sitemap/products.xml" is not callable: Controller "sylius.controller.sitemap:showAction" does neither exist as service nor as class.

**Comment by SquareInnov** [comment]
#233 This pull request can solve it

**Comment by stefandoorn** [comment]
Included in https://github.com/stefandoorn/sitemap-plugin/releases/tag/v2.1.0. Thanks!
