### ISSUE TITLE
2.1.0 is not compatible with php 7.4

### ISSUE THREAD

**Issue by t-n-y** [stefandoorn/sitemap-plugin#245]
Hi,

The 2.1.0 release is supposed to be compatible with php 7.4, but `SitemapController.php` construct use a comma at the end of the parameters so that doesn't work under php8

**Comment by stefandoorn** [comment]
Ah :-( Will look into that soon and tag accordingly. Obviously open to PR's as well for it to add PHP 7.4 support again. Probably something needs to change in the ECS settings to allow this.

**Comment by stefandoorn** [comment]
I think it's fixed by this release: https://github.com/stefandoorn/sitemap-plugin/releases/tag/v2.1.1

Could you let me know?

**Comment by t-n-y** [comment]
Seems ok, thanks !
