### ISSUE TITLE
Version with Sylius 1.13 support

### ISSUE THREAD

**Issue by mbenoukaiss** [stefandoorn/sitemap-plugin#257]
Hello

The latest version does not support sylius ^1.13 but the master branch does, so it is possible to use sylius ^1.13 and this plugin by requiring dev-master instead of a specific version but it is not ideal.

In the current state of the repository would it be possible to publish a version of master, or are there changes that need to be brought to master before ?

**Comment by stefandoorn** [comment]
Ah - I'm happy to prepare a tag that allows Sylius 1.13. My project isn't there yet, so it's always slightly harder to test. Can you confirm it does work properly on Sylius 1.13 (using `dev-master`)?

**Comment by mbenoukaiss** [comment]
We tested it and it works with Sylius 1.13, however we only use custom URL providers and don't use the default ones, so that is one thing we did not test

**Comment by stefandoorn** [comment]
Thanks, @mbenoukaiss

**Comment by stefandoorn** [comment]
I recall again the issue here, I wanted to make CI work on a range of Sylius / Symfony versions, but that took too much time and then paused it. 

I will release the Composer allowance in a bit, and look at CI later again.

**Comment by mbenoukaiss** [comment]
Thank you !
