### ISSUE TITLE
customer can see the sitemap on the website

### ISSUE THREAD

**Issue by benyang2015** [stefandoorn/sitemap-plugin#30]
like this:
https://www.reiss.com/rw/sitemap/

**Comment by stefandoorn** [comment]
This plugin focusses on providing a structured sitemap to use in tools like Google Webmaster Tools. The suggested sitemap is more customer / front-end tailored. I'll keep the issue open as Feature Request, but I'm currently not planning to integrate an HTML output view of the sitemap.

**Comment by stefandoorn** [comment]
@benyang2015 I've decided that this plugin will solely focus on the XML sitemap features, nothing HTML / front-end. I think it can be an useful feature, but I need to be able to support it also, so I like to keep this package focussed on a single purpose.
