### ISSUE TITLE
Symfony 3.2 deprecation

### ISSUE THREAD

**Issue by sweoggy** [stefandoorn/sitemap-plugin#31]
> User Deprecated: The "sylius.sitemap_builder"  service is private, getting it from the container is deprecated since  Symfony 3.2 and will fail in 4.0. You should either make the service  public, or stop using the container directly and use dependency  injection instead.

I believe caused by `$providers = $this->container->get('sylius.sitemap_builder')->getProviders();` at row 41 in SitemapLoader.php.

I suggest us to inject the `sylius.sitemap_builder` service into the `sylius.sitemap.routing_loader` service, no need to have it public that way.

**Comment by stefandoorn** [comment]
Sounds good to me, shouldn't give any BC also. Would you be able to submit a PR?

**Comment by sweoggy** [comment]
Will do
