### ISSUE TITLE
Pass parameter to static route

### ISSUE THREAD

**Issue by czende** [stefandoorn/sitemap-plugin#34]
Hi, I'm using bitbag CMS plugin and just want to pass `slug` parameter to the static route `bitbag_sylius_cms_plugin_shop_page_show` in your plugin. But still get "unrecognized option slug". Any hint how to properly pass slug to bitbag cms route in yml sitemap config?

Thank you!

**Comment by stefandoorn** [comment]
Hi, probably best is to make a BitBagCmsProvider to have full support for all CMS routes dynamic. I still have it on my todo list, but didn't have time yet. It should be stored in a separate plugin as a bridge imo. If you have interest in developing one, that would be great of course :) 

Anyway, short term: did you try the parameters key that can be supplied to a static route? That one should be able to take an array including the slug key. 

If it doesn't work, please copy also your config so I can have a better look.

**Comment by stefandoorn** [comment]
@czende Any tests results as suggested? I still need to look into it :(

**Comment by czende** [comment]
@stefandoorn Sorry, I've been busy. Yes, I tried pass the parameters key to a static route, but I'm still getting error `Unrecognized option "slug" under "sylius_sitemap.static_routes.1.parameters.0"`

Maybe @bitbager can help us?

**Comment by bitbager** [comment]
Sorry to say that, but I'm not the author 😢

**Comment by stefandoorn** [comment]
:-) Ok. I will try to look into it. If you have some time @czende, some failing test would already help (or a PR with a fix of course).

Next on the roadmap is to provide integration with CmsPlugin that is developed by @bitbager, but yeah.. need a bit more time to work on that :)
