### ISSUE TITLE
Upgrade lakion/api-test-case to 2 or higher for sylius 1.1.3

### ISSUE THREAD

**Issue by NikitaKharkov** [stefandoorn/sitemap-plugin#44]
So, the fact that I can't update to sylius 1.1.3 if I use your plugin. If it's easy to do - do it please. Thank in advance!

**Comment by stefandoorn** [comment]
Would you be able to provide a PR with the change? I won't be able to look into this this week probably.

**Comment by stefandoorn** [comment]
Done, currently available in `master` branch: https://github.com/stefandoorn/sitemap-plugin/commit/99520c7ccadee2a26627269f51dce73dc1cd33cb.
